- name: get oc location
  command:  "whereis oc"
  register: oc_location_result
  ignore_errors: false
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'
  tags: always 

- name: set oc location
  set_fact:
    oc_location: "{{ oc_location_result.stdout.split(':')[1] }}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'
  tags: always 

- name: get oc location
  command:  "which oc"
  register: oc_location_result
  ignore_errors: false
  when: ansible_distribution == 'MacOSX'
  tags: always 

- name: set oc location
  set_fact:
    oc_location: "{{ oc_location_result.stdout  | trim() }}"
  when: ansible_distribution == 'MacOSX'
  tags: always 

- name: Log in (obtain access token)
  community.kubernetes.k8s_auth:
    host: "{{ openshift_url }}"
    username: "{{ openshift_username }}"
    password: "{{ openshift_password }}"
    validate_certs: "{{ insecure_skip_tls_verify }}"
    state: present