---
# tasks file for quarkus-cafe-demo-role
- name: Configure settings environment using OpenShift token
  block:
    - name: Login Cluster
      include_tasks: login-to-cluster.yml
      tags: always 

    - name: check if project openshift storage project exists
      command: "{{ oc_location }} get project openshift-storage"
      register: ocs_project_result
      ignore_errors: true
      changed_when: false
      tags: quay

    - name: Check noobaa-db-pg-0
      k8s_info:
        kind: Pod
        label_selectors:
          - name = noobaa-db-pg-0
        field_selectors:
          - status.phase=Running
        host: "{{ openshift_url }}"
        validate_certs: "{{ insecure_skip_tls_verify }}"
        api_key: "{{ openshift_token }}"
      ignore_errors: true
      register: ocs_noobaa_status
      tags: quay

    - name: displaying noobaa-db-pg-0 deployment status
      debug:
        var: r_ocs_noobaa_status.resources[0].status.phase
      ignore_errors: false

    - name: End the play 
      meta: end_host

    - name: deploy openshift storage operator
      import_tasks: ./openshift-storage.yaml
      become: true
      when: 
        - ocs_project_result is failed
      tags: quay

    - name: Configure Quay 
      include_tasks: quay.yml
      tags: quay